### ISSUE TITLE
BAM index bug causes wrong data shown

### ISSUE THREAD

**Issue by oyvinev** [igvteam/igv.js#1280]
Hi,

I was made aware of a problem with a bam-file of ours, specifically that it did not match what was shown in standalone IGV. After digging through it, I found that the problem most likely lies in the BAM index reader. Below is shown the same file with and without index (data shown in `without-index.bam` is correct, verified with standalone IGV, samtools and sambamba):

![image](https://user-images.githubusercontent.com/4920368/110014444-15eb4680-7d23-11eb-8453-c64cad1414b8.png)

I'm using the latest versions of igvjs (problem is also confirmed with version 2.5.4):
![image](https://user-images.githubusercontent.com/4920368/110014580-416e3100-7d23-11eb-97ab-d8e6e5056a4e.png)

I know where little about the details of BAM, BGZF and BAM-index, but with my limited understanding, I'm suspecting that with the index it only reads data from a single block?

**Comment by oyvinev** [comment]
This is sensitive data, so I'm unfortunately not able to share the bam-file, but I'm happy to help both debugging it, or creating a non-sensitive example, if I can get some pointers on what to look for.

**Comment by jrobinso** [comment]
Well that is disturbing, thanks for the report.   I will try to reproduce it with public data.  Are you able to build and test from github, should I have something to test?   If not I can build for you.

**Comment by jrobinso** [comment]
From the screenshot it doesn't look like "wrong" data is shown, but that not all data is shown.   By that I mean the alignments that are shown look correct.   Also, they stop abruptlyafter a specific start position (that's how alignments are sorted).  I suspect the stopping point is at a compressed block boundary,  but I'm still trying to create a reproducible test case.

**Comment by jrobinso** [comment]
@oyvinev Since I can't reproduce this (yet) your help would be appreciated.   I just pushed a possible fix, or workaround, based on code inspection.   If it works it is useful information.   Could you try the version here, or pull from master and build?   http://igv.org/web/snapshot/dist/

Is there any unusual characteristics of your BAM file, that might be useful as I try to create one with the same problem?  Are the alignments very sparse with respect to the genome dimension, for example?   Perhaps exome or other targeted region data?

**Comment by oyvinev** [comment]
Thanks for the quick reply! I agree, it looks like it's just truncated, not "wrong".

I will build with this, and see if it has an effect.

The bam file is from exome capture but it's also been sliced heavily (to relevant variants +/- 4000). It's a total of 212k reads (77MB uncompressed bam).

**Comment by oyvinev** [comment]
Unfortunately, that did not resolve it. It does not hit that block.

I will try to figure out if this indeed is happening on a block "border", and if so, where that block goes missing.

**Comment by jrobinso** [comment]
@oyvinev OK thanks for test that is good information.    I'm combing though the comb today, its like archaeology.   This originated in "c" in samtools in a previous epoch.     The index is something like an R tree,  with each node called a "bin".    Its described in section 5.1 of the samtools spec. http://samtools.github.io/hts-specs/SAMv1.pdf.   The flow basically goes like this

1. Compute bin (node) numbers that might have alignments in the intervals
2. Use the "bin index" to find the "chunks" of the file that correspond to those bins.   A chunk can be thought of as a slice of the uncompressed file,  its not an individual compressed block.   This is a detail but confused me.
3. Optimizes the chunks by using the "linear" index, and combining adjacent chunks.

The problem could be in the 3rd step,  around line 200 in bam/bamIndex.js.    I will prepare a branch for you to pull with the optimization removed later today,  I have meetings until around noon Pacific Time.

**Comment by oyvinev** [comment]
Thanks a lot for looking into it, and for outlining the flow in
understandable lingo. I've also suspected the optimization there, but I'm
still banging my head against the wall that is the sam spec.

This isn't completely verified, but it seems like all the data is pulled
from the backend, which I guess suggests that something is indeed off in
step 3? Due to family commitments, I won't be able to verify this until
Monday (I'm on Central European time).

I'm fighting with the details off blocks, chunks and bins. They're running
out of synonyms...

fre. 5. mar. 2021, 17:27 skrev Jim Robinson <notifications@github.com>:

**Comment by jrobinso** [comment]
If by data you mean from the bam file, as opposed to the index file,  then that would implicate decoding the bams, rather than the index.   I know the bams are properly decoded when not indexed but the problem could be the loop through chunks.    

I'm glad its not just me that finds the sam spec a challenge.   I don't think you can understand it without looking at code.  I had the advantage of quizzing the author (Heng Li) about it but the understanding I achieve lasts about a day then I have to start over.   However to the specifics you mention, here's my understanding

* bin -- a node in the R tree
* chunk -- a region in the file which encodes some number of continuous alignments.   The boundaries are marked by "vpointers", which can be thought of as pointers to positions in the uncompressed file.   They aren't exactly that, but I find it useful to think of them that way (they are actually a composite of a pointer to the begginning of a compressed block, and an offset from the start of the uncompressed data from that block).
* block -- a compressed block of the file from bgzip.   

One way to think of a "chunk" is to consider it as a composite super-alignment,  the index could work with no chunks by indexing every individual alignment, but it would be enormous.   So the chunk is really the thing that is indexed, not individual alignments.

The block doesn't come into play until you are actually decoding the data,  its a gzip detail that is orthogonal to the index scheme.

**Comment by jrobinso** [comment]
@oyvinev
I've pushed 3 branches that might help us isolate this problem.  They are focused on chunk optimization.   If you could pull these and do a quick test it would be most helpful.  The branches are

1. no_optimization --  this does not optimization at all,  try this one first.   If it fails you do not need to try 2 and 3
2. no_linear -- does not use the linear index,  this will be slow
3. no_merging -- this one does not attempt to merge adjacent blocks
  
If these these branches do not fix the problem we can eliminate chunk optimization as a cause.    I will next examine the decoding and filtering of the bam records.

**Comment by oyvinev** [comment]
Hi Jim,

Unfortunately this did not resolve it. I'll do some more debugging, and see if I can pinpoint where the reads are lost.

I've done some work on parsing the bam-file manually using Python. Here are some findings:
- All overlapping alignments are in bin 9994.
- Two gzip blocks have overlapping alignments
     - Block 434 starting at 3142789
     - Block 435 starting at 3151559
- All alignments shown in the `with-index`-case, are a subset of the alignments shown in the `without-index`-case
- There are 37 paired alignments loaded with the index, and 98 paired alignments loaded without the index.

There appears to be only a single chunk ("merged === chunks"). The single chunk being 
```
{
   bin: 9994,
   minv: {
       block: 3090481,
       offset: 54499
   },
   maxv: {
       block: 3151559,
       offset: 47237
   }
}       
```

Is it strange that `chunk.maxv.block` is equal to the gzip block 435 start position (3151559)? Or is that expected?

I'm wondering if there is a chunk missing here...

**Comment by oyvinev** [comment]
Well, the `parseIndex` function see 1 chunk for bin 9994...

**Comment by oyvinev** [comment]
Wrote a BAI-parser, and I'm starting to wonder if the index-file is wrong:

![image](https://user-images.githubusercontent.com/4920368/110324365-24cd4400-8016-11eb-9a0a-c7982cafbe8d.png)

And iterating over the blocks in the bam-file:

![image](https://user-images.githubusercontent.com/4920368/110324377-2860cb00-8016-11eb-8ff7-d68d96a4ca60.png)

So the chunk ends at 3151559, but the block starting at this position contains alignments in that bin!

**Comment by oyvinev** [comment]
Pretty sure I found the bug. Parenthesis here are wrong: https://github.com/igvteam/igv-utils/blob/b01d4e5c6f1448e4b3abb955c813c1163c7b0bda/src/bgzf.js#L64

![image](https://user-images.githubusercontent.com/4920368/110333002-60214000-8021-11eb-8036-b591655ce6c5.png)

**Comment by oyvinev** [comment]
Confirmed that https://github.com/igvteam/igv-utils/pull/8 resolves it.

**Comment by oyvinev** [comment]
I guess it's this line that actually causes it to fail silently: https://github.com/igvteam/igv-utils/blob/b01d4e5c6f1448e4b3abb955c813c1163c7b0bda/src/bgzf.js#L32

**Comment by jrobinso** [comment]
Wow, great!   I was going to ask if you share just the index for the file,  there is no patient data in it,  but I guess I don't need it now.

**Comment by oyvinev** [comment]
I guess the problem only happens when byte 16 in the header of the gzip block is `0xff`, as this shortens the BSIZE (all other are correct). 

This was a very interesting deep dive into BAM and bgzf (although a bit complex for a novice). Thanks for the help, @jrobinso, and thanks for a great tool which provide so much value to our lab!

**Comment by jrobinso** [comment]
Kudos for finding that!  I'll leave this open until I merge and release the fix.

**Comment by oyvinev** [comment]
Hi @jrobinso. Do you have an ETA for the update?

**Comment by jrobinso** [comment]
Now released in 2.7.9.   Please give it a try
