### ISSUE TITLE
Possible optimization for gCNV data loading

### ISSUE THREAD

**Issue by ShifaSZ** [igvteam/igv.js#1417]
We integrated `igv.js` into [seqr](https://seqr.broadinstitute.org/) to visualize the genome data. The performance for the `gCNV` tracks is very slow. There are a couple of reasons for that: firstly, the igv.js loads all the rows (or features) in the current chromosome rather than just the rows required for the current view; secondly, it re-loads all the data when zooming in or out.
For example, as shown in the figure below, the scope to display is just 138 bp. And only a few rows of data must be enough. But it loads more than 600MB of data with 270 requests.
![image](https://user-images.githubusercontent.com/33550059/140985219-7f1979cf-871e-4301-ac6d-644b93bffa68.png)

Is it possible to optimize the `igv.js` to just load the data in need?

**Comment by jrobinso** [comment]
Did you set a visibilityWindow?

**Comment by jrobinso** [comment]
Reloading the data looks like a bug, please confirm you are using the latest release and I will look into that.  If you don't set a visibilityWindow loading a whole chromosome is normal, but it should not then reload the data if you zoom out.  I will look into that if you confirm this is the latest version.

**Comment by jrobinso** [comment]
@ShifaSZ it would help a lot of you could give me a test case,  you can send a link to data by Broad email, it won't be shared.

**Comment by ShifaSZ** [comment]
I tried both setting and not setting a visibilityWindow. It has the same behavior. I'm figuring out how I can give you a test case because you may need access to certain Google buckets.

**Comment by ShifaSZ** [comment]
You may try this link https://seqr.broadinstitute.org/project/R0555_seqr_demo/saved_variants/family/F031959_demofamily1
There is a `SHOW gCNV` button in the middle of the screen. Click on the button to show the IGV.

**Comment by jrobinso** [comment]
My Broad email /google id is jrobinso (at) broadinstitute dot org.   We might need Ben's @bw2 help with this.

**Comment by jrobinso** [comment]
@ShifaSZ ok got it.   I'll try to see what's going on here, and pull @bw2 in if needed.

**Comment by jrobinso** [comment]
@ShifaSZ Could you confirm for me what version of igv.js is in use here?

**Comment by ShifaSZ** [comment]
The igv.js version is "2.10.1".

**Comment by jrobinso** [comment]
@ShifaSZ @bw2 OK there is some issue with indexed files specific to the gcnvTrack,  not the fault of Ben it just evolved that way.   I will sort this out.   When its working you will need to decide on a visibilityWindow appropriate for this data, but first let me get it working.

**Comment by jrobinso** [comment]
OK here's part of the issue, which I do need Ben's @bw2 hep with.  The gcnvTrack queries for all features for the entire chromosome irrespective of visibility window, and then does some logic to slice it to what's requested.   The question is why does it do this?   I'm going to assume there is no reason to do this, but I might be missing some subtleties on how this track works.

```
    async getFeatures(chr, start, end) {
        const chrFeatures = await this.featureSource.getFeatures({chr, start: 0, end: Number.MAX_VALUE});
        let prevIndex = undefined;
        let nextIndex = undefined;
        for (let i = 1; i < chrFeatures.length - 1; i++) {
            if (prevIndex === undefined && chrFeatures[i].end > start) {
                prevIndex = i - 1;
            }
            if (nextIndex === undefined && chrFeatures[i].start > end) {
                nextIndex = i + 1;
                break;
            }
        }
        if (prevIndex === undefined) prevIndex = 0;
        if (nextIndex === undefined) nextIndex = chrFeatures.length;
        return chrFeatures.slice(prevIndex, nextIndex);
    }
```

**Comment by jrobinso** [comment]
Also,  I'm seeing a lot of warnings like this in the example dataset

```
chr3:108563025-108563342 row contains 14 sample columns instead of the expected 1797 columns. Skipping...
gcnvDecoder.js:30 chr3:113268202-113268543 row contains 1686 sample columns instead of the expected 1797 columns. Skipping...
gcnvDecoder.js:30 chr3:119619466-119619750 row contains 1795 sample columns instead of the expected 1797 columns. Skipping...
gcnvDecoder.js:30 chr3:122427441-122427814 row contains 27 sample columns instead of the expected 1797 columns. Skipping...
gcnvDecoder.js:30 chr3:125110092-125110816 row contains 1611 sample columns instead of the expected 1797 columns. Skipping...
gcnvDecoder.js:30 chr3:128813230-128814896 row contains 1343 sample columns instead of the expected 1797 columns. Skipping...
gcnvDecoder.js:30 chr3:130993835-130994196 row contains 1322 sample columns instead of the expected 1797 columns. Skipping...
```

**Comment by jrobinso** [comment]
I just pushed a fix for the reloading of features, it was due to the use of Number.MAX_VALUE for the query end noted above.  However, visibilityWindow cannot be used as it is necessary for this track to load all the feature for a chromosome as currently implemented.    That is because the feature just out of view on both ends is needed to reliably draw the track.  There isn't any way to know where those features are in advance.    You might talk to Ben to see if he has ideas on this.   In any rate its better now with feature caching working, after the initial load, but that is taking ~20 seconds for chr3.

Also please note the warnings about skipping rows noted above.

**Comment by ShifaSZ** [comment]
I tried version "2.10.4". The loading time for a gCNV track on seqr reduces to less than a few seconds. Thanks, Jim @jrobinso.
We still have a related issue that `parseFloat()` is very slow on seqr. It is much faster if we change it to `Number()` for `decodeGcnv` in IGV. It is not an issue for IGV. It's appreciated if you can help us to figure out why our `parseFloat` is slow.

**Comment by jrobinso** [comment]
@ShifaSZ  Where is the parseFloat happening, and to you mean the built-in javascript parseFloat() is slow, or a custom function?

**Comment by jrobinso** [comment]
Also, related, I don't understand what you mean by "it is much faster if we change it to Number()"

**Comment by ShifaSZ** [comment]
I tried to change "parseFloat" to "Number" in the last line below. The time becomes much shorter from the data is downloaded to the track is displayed.
```
// from file js/gcnv/gcnvDecoder.js
function decodeGcnv(tokens, header) {

    const columnNames = header.columnNames;
    if(!columnNames) {
        throw Error("Sample names are not defined.   Missing column headers?");
    }
    const sampleCount = columnNames.length - 3;

    const chr = tokens[0];
    const start = parseInt(tokens[1]);
    const end = parseInt(tokens[2]);
    const values = tokens.slice(3).map(parseFloat);
```

**Comment by ShifaSZ** [comment]
> @ShifaSZ Where is the parseFloat happening, and to you mean the built-in javascript parseFloat() is slow, or a custom function?

It is the built-in javascript parseFloat().

**Comment by jrobinso** [comment]
Well that's surprising but good to know.   With normal numeric strings, which you have, Number and parseFloat should give the same answer, so use Number.   I can make the change,  I will review the use of parseFloat generally.   Leave this issue open for now as a reminder.

This webpage is useful, reloading it multiple times I find Number is sometimes faster than parseFloat,  but not always, and usually not more than 25% faster.    http://phrogz.net/js/string_to_number.html

**Comment by ShifaSZ** [comment]
It must be okay to use parseFloat() for IGV because the performance is good on other web applications. We need to figure out what happens to seqr.

**Comment by jrobinso** [comment]
@ShifaSZ Possibly you are loading a lot more floating point data than the typical application, so you notice it more.   How much of a performance hit is it,   2X as long,  10X?   I plan to convert to Number() after you pointed this out,  its should be a little faster for everyone.

**Comment by bw2** [comment]
Sorry to miss this thread earlier. Jim, you're right - "it is necessary for this track to load all the feature for a chromosome as currently implemented. That is because the feature just out of view on both ends is needed to reliably draw the track. There isn't any way to know where those features are in advance."

I think the easiest/best solution to improve performance is for us to split the data files so that there are fewer than N samples per track, where N = ~200 in my experience. It's reasonable that performance degrades beyond a certain N (just like if you had a huge .bed file with an unusually large number of features).
