### ISSUE TITLE
Annotation track keeps disappearing when I scroll around

### ISSUE THREAD

**Issue by AlexdeMendoza** [igvteam/igv.js#1633]
Dear IGV team, 

I have some sessions on IGV app and I host my files on Globus (a cloud storage used by many universities). I didn't use to have any problem, but this week I realised that the annotation file keeps not loading any genes when I scroll around or change genomic position. Just when I open my session I do see the genes, but then they disappear and I can't do anything about it. Even if I load the local file (sorted gff with index done with IGVtools), it happens the same. Since this wasn't happening before, I suspect this might be on your end. 

Thanks, 

A.

**Comment by jrobinso** [comment]
OK I can reproduce the panning issue (scrolling around) now,  working on a fix.

**Comment by jrobinso** [comment]
This is fixed, release 2.15.5 of igv.js.   The webapp (igv.org/app) has been updated as well.

**Comment by carlosribas** [comment]
I'm afraid this issue is not fully resolved. I'm using release 2.15.5 and I still have this problem, I need to click on the search icon to update tracks.

You can see this issue when opening this html page:

```
<html>
  <body>
    <rnacentral-genome-browser></rnacentral-genome-browser>
    <script type="text/javascript" src="https://rnacentral.github.io/rnacentral-genome-browser/build/genome-browser.js"></script>
  </body>
</html>
```

this project is still under development (it works only with homo_sapiens)

**Comment by jrobinso** [comment]
I can see the problem in your example, but I can't reproduce it with igv.js.   Its hard to say what's going on as I don't have access to your app.  The first step is to reproduce the issue with a stand-alone igv.js,  see the example below

```
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>issue 1633</title>
</head>

<body>

<script type="module">

    import igv from "https://cdn.jsdelivr.net/npm/igv@2.15.5/dist/igv.esm.js"

    var options =
        {
            genome: "hg38",
            locus: "X:73,819,307-73,856,333",
            tracks: [
                {
                    type: 'annotation',
                    format: 'gff3',
                    url: 'https://ftp.ebi.ac.uk/pub/databases/RNAcentral/.ensembl/Homo_sapiens.GRCh38.109.chr.sorted.gff3.gz',
                    indexURL: "https://ftp.ebi.ac.uk/pub/databases/RNAcentral/.ensembl/Homo_sapiens.GRCh38.109.chr.sorted.gff3.gz.tbi",
                    height: 600
                },
                {
                    type: 'annotation',
                    format: 'gff3',
                    url: 'https://ftp.ebi.ac.uk/pub/databases/RNAcentral/.ensembl/homo_sapiens.GRCh38.sorted.gff3.gz',
                    indexURL: "https://ftp.ebi.ac.uk/pub/databases/RNAcentral/.ensembl/homo_sapiens.GRCh38.sorted.gff3.gz.tbi",
                    height: 600
                }
            ]
        }

    var igvDiv = document.getElementById("igvDiv")

    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
        })

</script>
</body>
</html>
```

**Comment by jrobinso** [comment]
Is it possible your containing app is eating mouse events, in particular mouse-up?

**Comment by carlosribas** [comment]
Using your example I can see that indeed the problem has been resolved, I will investigate this error from my side.

My app runs as an embeddable component in a Shadow DOM. I'll run some tests and let you know if I find out what the problem is. 

Thank you!

**Comment by jrobinso** [comment]
The repaint is triggered after dragging on a mouse up event.   If that event is not making it to igv.js then it would cause the symptoms you are seeing.

**Comment by carlosribas** [comment]
I have no idea why my app isn't handling mouse up events. Other events, such as the click that displays the popover, work normally. I'll keep debugging

**Comment by jrobinso** [comment]
Well that's just a guess on my part.   If you import igv.esm.js (note not igv.esm.min.js) you can set a breakpoint at this line, approximate line numb 25064,  and see if it gets called on  mouseup

```
this.browser.endTrackDrag();
```

**Comment by carlosribas** [comment]
I can see that its called on onclick (image attached), but not on mouseup. I'm still trying to understand the reason...
<img width="1504" alt="Screenshot 2023-05-09 at 14 06 25" src="https://github.com/igvteam/igv.js/assets/8561563/1d8eabb0-c045-4501-82d2-df3ccee687e3">

**Comment by jrobinso** [comment]
It is curious.  Some other element could be listening for "mouse up" and
not bubbling it up, but that would need to be a child element of the IGV
dom element receiving the event.

**Comment by carlosribas** [comment]
Ta-da! I found the guilty one! I'm using `trackDefaults` with the following lines:

```
trackDefaults: {
  annotation: {
    minHeight: 100,
    maxHeight: 600,
    autoHeight: true
  }
}
```

and it is the `autoHeight: true` that is causing this issue. If you add these lines in the code you sent me you will be able to see this problem

**Comment by jrobinso** [comment]
Thanks for the investigation!  This is going to take some redesign.
