### ISSUE TITLE
CORS policy for hg19_alias.tab 

### ISSUE THREAD

**Issue by youknow16** [igvteam/igv.js#1887]
I'm using _igv.js_ on my website and I have a copy of the _igv.min.js_ on my server which I use.
Recently I get this error:

Access to XMLHttpRequest at 'https://igv.org/genomes/data/hg19/hg19_alias.tab' from origin 'http://myserver.com:456' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

How can I self-host this file? Since the setup for using _igv.js_ is to only import _igv.min.js_ , there is no place for me to use the local version of _hg19_alias.tab_ and not hit your servers!

**Comment by jrobinso** [comment]
This should be fixed now.   If you wanted to host your own genome data you can, see the user guide, particularly the "genomeList"  and "loadDefaultGenome" properties described here:

https://igv.org/doc/igvjs/#Browser-Creation/

**Comment by youknow16** [comment]
Thanks. I'll work on hosting the files myself.
Meanwhile I still see the same error. Just to report.

**Comment by youknow16** [comment]
After adding genomeList, I'm getting a new error:  

![igv](https://github.com/user-attachments/assets/165bc86d-2ab5-44ac-a09e-40001bb012e2)

**Comment by jrobinso** [comment]
Looks like a problem with your json file.

**Comment by jrobinso** [comment]
RE the original error, could you try clearing your browser cache?

**Comment by youknow16** [comment]
Reverting back to the previous file (removing genomeList), everything works fine now. Thanks!
