### ISSUE TITLE
bgzip/tabix net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#254]
Hi,

First I wanted to thank you for igv.js!

I've noticed a re-occurring (yet rare) error with some bgzip/tabix files.  

The suspect file will load in just fine, and will render most ranges.  However some ranges will fail and instead error out with a net::ERR_CONTENT_LENGTH_MISMATCH.  This seems to happen when the range requested either has no data, or has very little data...

I noticed this especially today with a BED file roughly 1.5M in size (uncompressed).
This file generally works as uncompressed or bgzip/tabix/idx across all ranges.
If I take a random subset of this file (50%) and bgzip/tabix, then I will get CLM errors for most ranges.

e.g. sample BED to reproduce error
chr1	1	1000000	a	1
chr19	47000000	48000000	b	1
chr19	47500000	48500000	c	1
chr19	48000000	49000000	d	1
chrX	1	20000000	e	1

If the above bed is loaded as a uncompressed BED, it works fine (as expected) across all ranges.
If the above bed is loaded as a bgzip + idx, it fails with a CLM error.
If the above bed is loaded as a bgzip + tbi, it fails with a CLM error.

Error is reproducible with current master (e5d81bd6f2bd00e96e47a32b9f16d9b966864e6f).

Thanks!

**Comment by jrobinso** [comment]
OK, thanks for the example, it really helps.  Could you attach that bed file?  I've seen subtle errors due to whitespace differences from copy/paste.

**Comment by blajoie** [comment]
Sure thing - here they are.

[badbed.bed.gz](https://github.com/igvteam/igv.js/files/448482/badbed.bed.gz)

**Comment by jrobinso** [comment]
I just pushed a change that *might* fix the problem.  I say might because I couldn't reproduce the symptoms you describe with the test bed file.   Rather, I just saw nothing.    If this doesn't fix the problem could you attach a bgzipped file with the tabix index?  You'll probably have to zip them, I'm not sure what file types are allowed as attachments.

**Comment by blajoie** [comment]
Awesome Jim - thanks!  I will pull down this latest commit and do some thorough testing tomorrow.
Should I need to attached a larger file that can reproduce the issue, I can host on dropbox. 

Will report back soon, appreciate it!

**Comment by jrobinso** [comment]
Its a good idea, btw, to set a "visibilityWindow" property on dense tabix
files if you are not already.  It defaults to whole chromosome.   This is
not the cause of your problem,  just a note.

**Comment by blajoie** [comment]
Yes absolutely - I am already making good use of the visibilityWindow property :)  

Though in the future it might be nice to instead default it to something like N number of objects to be rendered on screen?  e.g. dynamic threshold based on local density of the track?

 Or even a method to sample from a overly-dense track should a user request far too many objects to be rendered.  (rendering only some shapes may be better than none/crashing the browser - given of course that this coincides with a clean warning/alert!)

**Comment by jrobinso** [comment]
The visibilityWindow is not primarily for rendering, but to reduce the # of
objects fetched and loaded.  The cost of rendering on a canvas is
negligible.   There is no easy way to know the local density of the track
in advance, that is prior to loading it, thus the property.

There should probably be some guidelines in the doc on good values, but for
now I would advise erring on the small side.   It really becomes an issue
for VCF files with many genotypes,  or very dense bed files such as dbSnp.

**Comment by blajoie** [comment]
Ah yes, of course this makes sense.  Perhaps I was thinking about a more complicated strategy - that will come later :)

Back to this issue, unfortunately your fix did not solve the issue.
Yesterday I suspected an issue with the tabix/block + range_request.

I think it is solved now.
See my latest commit:
https://github.com/blajoie/igv.js/commit/9a3edb31bf2365a923603784e21a3ed051051788

This was the line causing the issue (featureFileReader.js)
```
endPos = block.maxv.block + (index.tabix ? MAX_GZIP_BLOCK_SIZE + 100 : 0),
```

This has the potential to set the range-request (endpos) beyond the maxBlock, which would result in the CLM error.

I modified bamIndex.js to include a maxBlock param, and then made sure to always check the block-bounds when setting the startpos/endpos for the range-request.
Everything seems to work perfectly now.

One way to demo this (using current master) would be to take a gencode.v18.collapsed.bed file, bgzip + tabix it, load into igv.js and then click to somewhere on the end of chrX.  The "block.maxv.block + (index.tabix ? MAX_GZIP_BLOCK_SIZE + 100 : 0)," causes the endPos to be set beyond the maxBlock bound, resulting in the CLM error.

```
wget https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed
bgzip gencode.v18.collapsed.bed
tabix -p bed gencode.v18.collapsed.bed.gz
```

**Comment by jrobinso** [comment]
Yes, thanks, that's great.   I can probably copy/paste that but would you be able to submit a pull request?

**Comment by jrobinso** [comment]
Never mind pull request this time,  I copy/pasted.   I'm not sure why that extra "100" is added, its been a long time since that code was looked at.  Its possible that is not needed at all, but your fix works.   Thanks again.

**Comment by blajoie** [comment]
Not sure either why the +100 is there.  I don't think it is necessary, but I also found it referenced in other sections of code, so I left it for the time being.  Glad the change worked out!  Will PR next time.

**Comment by blajoie** [comment]
Hi Jim,

I seem to be still having an issue with this.
Does this BED render for you? For me, I cannot see anything, no errors either (similar to your observation above?)

The attached bed.gz/bed.gz.tbi is simply:

```
chr1    176000000       196000000       good_1
chr1    179000000       199000000       good_2
chr1    187000000       224000000       good_3
chr1    189000000       199000000       good_4
chr1    195000000       197000000       good_5
chr4    93000000        166000000       bad_1
chr4    117000000       146000000       bad_2
chr4    118000000       190000000       bad_3
chr4    122000000       190000000       bad_4
chr4    129000000       143000000       bad_5
chr4    135000000       190000000       bad_6
chr4    139000000       190000000       bad_7
```

[brokenbed.tar.gz](https://github.com/igvteam/igv.js/files/463278/brokenbed.tar.gz)

**Comment by jrobinso** [comment]
This is a different issue.  The structure of the tabix index itself is unexpected,  particularly the first bin  for each chromosome which is the only bin in this file.   Looking at it.

**Comment by jrobinso** [comment]
OK, this should be fixed (the "fix" for 254 was actually the cause, as we now know this was a server side problem.

**Comment by blajoie** [comment]
OK - to confirm, on your end - these small beds are still an issue, correct? (tabix index related)

For badbed, I can see the few blocks in chr19, but cannot see the chr1 or chrX block.
For broken_bed, I cannot see the chr1 or chr4 blocks.
Just trying to nail down my server config issues vs js issues.

I am now using the headers sent via igv.js, previously the exac-like-config would set new response headers which caused the issue.  

-

On an unrelated note - I am also seeing something else unexpected.
I am using the below (Broad-supplied) file, either as a non-indexed BED, or as tabix + bgzip bed

```
https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed
bgzip gencode.v18.collapsed.bed
tabix -p bed gencode.v18.collapsed.bed.gz
```

Top track is gencodev18 bedgz+tbi, bottom is raw unindexed gencodev18 bed.
If you zoom to the beginning of chr1, some bytes/lines of data are missing on my end?  Can you replicate?
![bedgz-vs-bed-bug](https://cloud.githubusercontent.com/assets/8889420/18395159/2e9fd8ce-7672-11e6-8667-77f4ee7040c2.png)

I've tracked this down to line 174 of featureFileReader.js
slicedData = startOffset ? inflated.slice(startOffset) : inflated;

I've modified as such:
```
// bug ?
//slicedData = startOffset ? inflated.slice(startOffset) : inflated;
slicedData = inflated;
```
Slicing by the startOffset seems to put us ahead of where would like to be in the bytearray?
Perhaps the startOffset is incorrect here?
Removing the slice, fixes the issue, and now both the bed and bed.gz+tbi show correctly.
![bedgz-vs-bed-fixed](https://cloud.githubusercontent.com/assets/8889420/18395161/30a12128-7672-11e6-8e98-779d1abb12c2.png)

**Comment by jrobinso** [comment]
Hi,  everything is fixed, small and large beds, in the IGV end against an apache server.   I don't think there are any outstanding issues.  I tested "brokenbed".   If you'll send the request and response headers for "brokenbed" when zooming in where there are features I'll have a look at it.

On the other issue, I will look at it but it will be this evening.   Can you open a new issue,  you don't have to replicate everything just reference this one.     Apologies for the issues,  and thanks for your persistence.

**Comment by blajoie** [comment]
When viewing broken_bed.gz I produce the following request/response.

```
-request-
Content-Length:
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Connection: keep-alive
Range: bytes=0-64999
Dnt: 1
Accept: */*
Accept-Language: en-US,en;q=0.8
Content-Type:
Accept-Encoding: gzip, deflate, sdch

-response-
Content-Disposition: attachment; filename="broken_bed.bed.gz"
Content-Transfer-Encoding: binary
Accept-Ranges: bytes
Content-Range: bytes 0-170/171
Content-Length: 171
```

**Comment by jrobinso** [comment]
OK, thanks.  Offhand the Content-Disposition response header looks odd.
You are not returning the file as an attachment.   Any idea where that
comes from?

Here's the responses I see (Apache)

Request:

   1. Accept:
   */*
   2. Accept-Encoding:
   gzip, deflate, sdch
   3. Accept-Language:
   en-US,en;q=0.8
   4. Cache-Control:
   no-cache
   5. Connection:
   keep-alive
   6. Cookie:
   Idea-26de161c=c80f549d-e910-41a9-b3f3-a45de3ff8521; __utmt=1;
   __utma=111872281.669019015.1472700939.1473442186.1473476553.9;
   __utmb=111872281.1.10.1473476553; __utmc=111872281;
   __utmz=111872281.1472700939.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
   7. Host:
   localhost
   8. Pragma:
   no-cache
   9. Range:
   bytes=0-65536
   10. Referer:
   http://localhost/igv-web/dev/igv-dev.html
   11. User-Agent:
   Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N)
   AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile
   Safari/537.36

Response:

   1. Accept-Ranges:
   bytes
   2. Connection:
   Keep-Alive
   3. Content-Length:
   171
   4. Content-Range:
   bytes 0-170/171
   5. Content-Type:
   application/x-gzip
   6. Date:
   Sat, 10 Sep 2016 03:02:53 GMT
   7. ETag:
   "ab-53c0d0e32b980"
   8. Keep-Alive:
   timeout=5, max=100
   9. Last-Modified:
   Fri, 09 Sep 2016 06:14:14 GMT
   10. Server:
   Apache/2.4.16 (Unix)

**Comment by jrobinso** [comment]
Reopening this -- I can reproduce the "bad bed" problem,  but not the "broken bed".

**Comment by jrobinso** [comment]
Well, the "bad bed" problem (no features on 19 and chrX)  was unrelated to the server content-length issue, it was a bona-fide bug.   There was an error in the logic used for comparing "virtual pointers" when using the linear index.

**Comment by blajoie** [comment]
Fantastic - thanks Jim!

I will pull down this latest commit and then do a bit more testing.
I think most of my server issues (incorrect response) are now resolved.

Appreciate your help with !
Perhaps the broken_bed issue was a result of both my server mis-config + this bug.

Will report back soon.

**Comment by jrobinso** [comment]
The combination of issues was certainly confusing things,  but "broken bed"
was an igv bug,  I don't think the server impacted this.
