### ISSUE TITLE
Custom Fasta URL

### ISSUE THREAD

**Issue by kfneto** [igvteam/igv.js#379]
I am trying to use a custom fasta url that needs a token authorization, same as when loading files like bam. 

How can I do it?

**Comment by jrobinso** [comment]
Could you be more specific with your question?   Do you want to set a header, or add a token to a URL.  If the latter just add it.

**Comment by kfneto** [comment]
I want to set a header with the Authorization Bearer Token.

**Comment by jrobinso** [comment]
OK, see this:
https://github.com/igvteam/igv.js/wiki/OAuth-Support--(beta-only)

Even if you are not using OAuth on the backend you can use the oauthToken
parameter to send the token.   Note that this only works in the "beta"
igv.js (latest code).

If using the released version there is a generic "headers" parameter for
the track config object.   I haven't tried this  but the following should
work in your track configuration.

{
     .....
      headers: {
             'Authorization':  'Bearer ' +  token;
      }
}

**Comment by kfneto** [comment]
I've tried to add the header above but when trying to get .fai from fasta_url I get the error of unauthorized. So, I should add the header also when getting .fai file, but this is not exposed in the plugin, right? How can I correct this?

**Comment by jrobinso** [comment]
Apologies,  I just discovered that the config option is not applied to
reference objects (fasta, cytoband).   Working on a fix now.

**Comment by jrobinso** [comment]
This should be fixed now in the master branch,  and the beta distribution

https://igv.org/web/beta

With this distribution you must include the "underscore" library,  

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>

**Comment by kfneto** [comment]
Hi, thanks for the solution.
When trying to use the beta version, I get the following exception:

DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('div"') is not a valid name.

**Comment by jrobinso** [comment]
Could I see the javascript you use to initialize igv.js,  or alternatively
the whole page?

**Comment by kfneto** [comment]
```
var div = document.getElementById("igvs");

$scope.generateIgvJs = function() {
      if(p)
        p.destroy()

      var options = {
        showCenterGuide: true,
        showCursorTrackingGuide: false,
        reference: {
            id: "hg19",
            fastaURL: API_PREFIX + '/igv'+ $scope.data.url_fasta,
            cytobandURL: "//igv.broadinstitute.org/genomes/seq/b37/b37_cytoband.txt",
            headers: {
              Authorization: 'Bearer ' + $auth.getToken()
            }
        },
        trackDefaults: {
            bam: {
                coverageThreshold: 0.2,
                coverageQualityWeight: true
            }
        },
        tracks: [
            {
              type: 'alignment',
              samplingDepth: 500,
              // samplingWindowSize: 41,
              colorBy: 'strand',
              name: $scope.data.name,
              url: API_PREFIX + '/igv'+ $scope.data.url_bam,
              indexUrl: API_PREFIX + '/igv' + $scope.data.url_bai,
              format: "bam",
              headers: {
                Authorization: 'Bearer ' + $auth.getToken()
              }
            },
            {
                name: "Genes",
                url: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed",
                index: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed.idx",
                displayMode: "COLLAPSED"
            }
        ]
      }

      var browser = igv.createBrowser(xxx, options);
      browser.search($scope.data.chromosome + ':' + (parseInt($scope.data.start) - 1) + '-' + 
      parseInt($scope.data.stop))
      var browser = igv.createBrowser(div options);

}

$scope.generateIgvJs();
```

**Comment by jrobinso** [comment]
OK, thanks, that was helpful.   I couldn't reproduce your problem on my Mac but think I found the cause via code inspection.   So I think it's fixed now but don't know for sure since I could not reproduce it.

A couple of minor problems with your initialization code.  First,  you should call igv.createBrowser only once.  Secondly,  instead of calling "search" you should specify an initial location using the "locus" parameter.   See the example below,  modeled after yours.   The createBrowser code is asynchronous and might not be ready for the search command immediately.

        var options = {
            showCenterGuide: true,
            showCursorTrackingGuide: false,
            locus: "8:128,747,315-128,754,680",
            reference: {
                id: "hg19",
                fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/1kg_v37/human_g1k_v37_decoy.fasta",
                cytobandURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/b37/b37_cytoband.txt"
            },
            trackDefaults: {
                bam: {
                    coverageThreshold: 0.2,
                    coverageQualityWeight: true
                }
            },
            tracks: [
                {

                    url: 'https://data.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam',
                    name: 'Brain (BodyMap)

                },
                {
                    name: "Genes",
                    url: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed",
                    index: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed.idx",
                    displayMode: "COLLAPSED"
                }
            ]
        }

        var browser = igv.createBrowser('#igvDiv', options);

**Comment by kfneto** [comment]
I've just did what you wrote above, but the error still remains. When changing to the plugin's release version, the error disappears. But I still can't do the auth for fasta file. Can you please move this last commit for master release?

```

$scope.generateIgvJs = function() {

      if(p)
        p.destroy()

      var options = {
        showCenterGuide: true,
        showCursorTrackingGuide: false,
        locus: $scope.data.chromosome + ':' + (parseInt($scope.data.start) - 1) + '-' + parseInt($scope.data.stop),
        reference: {
            id: "hg19",
            fastaURL: API_PREFIX + '/igv'+ $scope.data.url_fasta,
            cytobandURL: "//igv.broadinstitute.org/genomes/seq/b37/b37_cytoband.txt",
            headers: {
              Authorization: 'Bearer ' + $auth.getToken()
            }
        },
        trackDefaults: {
            bam: {
                coverageThreshold: 0.2,
                coverageQualityWeight: true
            }
        },
        tracks: [
            {
              type: 'alignment',
              samplingDepth: 500,
              // samplingWindowSize: 41,
              colorBy: 'strand',
              name: $scope.data.name,
              url: API_PREFIX + '/igv'+ $scope.data.url_bam,
              indexUrl: API_PREFIX + '/igv' + $scope.data.url_bai,
              format: "bam",
              headers: {
                Authorization: 'Bearer ' + $auth.getToken()
              }
            },
            {
                name: "Genes",
                url: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed",
                index: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed.idx",
                displayMode: "COLLAPSED"
            }
        ]
      }

      igv.createBrowser("#pileup", options);
    }

    $scope.generateIgvJs();
```

**Comment by jrobinso** [comment]
Did you clear you browser cache?

**Comment by jrobinso** [comment]
Also, could you give me the exact error message(s) from the console?

**Comment by kfneto** [comment]
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('div"') is not a valid name.
    at Function.jQuery.parseHTML (http://0.0.0.0:9000/bower_components/jquery/dist/jquery.js:9774:20)
    at jQuery.fn.init (http://0.0.0.0:9000/bower_components/jquery/dist/jquery.js:2993:33)
    at jQuery (http://0.0.0.0:9000/bower_components/jquery/dist/jquery.js:98:10)
    at createZoomInNotice (https://igv.org/web/beta/igv-beta.min.js:1:375821)
    at igv.Viewport.initializationHelper (https://igv.org/web/beta/igv-beta.min.js:1:377783)
    at new igv.Viewport (https://igv.org/web/beta/igv-beta.min.js:1:375636)
    at https://igv.org/web/beta/igv-beta.min.js:1:332349
    at Function.m.each.m.forEach (https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js:5:2350)
    at new igv.TrackView (https://igv.org/web/beta/igv-beta.min.js:1:332270)
    at igv.Browser.addTrack (https://igv.org/web/beta/igv-beta.min.js:1:83966)

**Comment by jrobinso** [comment]
Bingo.   That was definitely a bug, but the browsers on the Mac just don't seem to care.   I fixed that one, if you get another please post the console messages again.   Also, if you change to "igv-beta.js" instead of "igv-beta.min.js"  it will give meaningful line numbers.   In this case it didn't matter.

I will patch the headers fix into the release branch, but not until I (or you) can verify its working.

**Comment by jrobinso** [comment]
Oh, try again, you might need to clear you browser cache to be sure you get the latest igv-beta.   Shouldn't need to, but if it fails try clearing the cache.

**Comment by kfneto** [comment]
Yes!!! It worked!!! Thanks so much!!! ;)

**Comment by jrobinso** [comment]
OK, great.   I'll close this, but open another tissue if you have more problems.
