### ISSUE TITLE
no luck creating TAIR10 gene annotation track

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#507]
After a few hours trying to recreate the solution reached here - [issue 241](https://github.com/igvteam/igv.js/issues/241) - 
and failing, maybe it's time to ask for help.
I obtained the same ````Araport11_genes.20150701.gff3.gz```` file, sorted it, created an index, and used this track configuration:

           {name: 'Genes TAIR10',
            type: 'annotation',
            visibilityWindow: 500000,
            url: "http://trena.systemsbiology.net/tair10/Araport11_genes_sorted.20150701.gff3.gz",
            displayMode: 'EXPANDED',
            height: 300,
            format: 'gtf'
            },

I see the Track Label, but no track.    I also tried to use the TAIR10 genome track downloaded (behind the scenes) by igv desktop, but failed to get that to work either.

I used the latest igv.js version from github, grunt running locally.  There are no errors in the javascript console.    

Any advice?

**Comment by paul-shannon** [comment]
I stumbled upon the solution.   TAIR spells chromsomes "ChrN".  That capital "C" leads to a silent failure by igv.js.  In case it will someday be helpful to others, here are some processing steps to create a useable gene annotation track from the tair10.genome downloaded with the help of igv desktop:
````
unzip ~/igv/genomes/tair10.genome
   # copy TAIR10_genes.gff3 to a work directory; cd there
sort -k1,1 -k4,4n  TAIR10_genes.gff3 -o  TAIR10_genes.sorted.gff3
cat TAIR10_genes.sorted.gff3 | sed -e "s/Chr/chr/" > TAIR10_genes.sorted.chrLowered.gff3
   # start R 
library(Rsamtools)
file <- "TAIR10_genes.sorted.chrLowered.gff3"
file.gz <- sprintf("%s.gz", file)
bgzip(file, file.gz, overwrite=TRUE)
print(indexTabix(file.gz, format="gff"))  # "TAIR10_genes.sorted.chrLowered.gff3.gz.tbi"
ls -l  TAIR10_genes.sorted.chrLowered.gff3*
     -rw-r--r--  1   37798289 Dec 27 13:04 TAIR10_genes.sorted.chrLowered.gff3
     -rw-r--r--  1      4371153 Dec 27 13:05 TAIR10_genes.sorted.chrLowered.gff3.gz
     -rw-r--r--  1          87312 Dec 27 13:05 TAIR10_genes.sorted.chrLowered.gff3.gz.tbi
scp TAIR10_genes.sorted.chrLowered.gff3.gz*  to your CORS and ranges configured webserver

````
Here is a sample track configuration:
````
              tracks: [
                 {name: 'Genes TAIR10',
                  type: 'annotation',
                  visibilityWindow: 500000,
                  url: "http://trena.systemsbiology.net/tair10/TAIR10_genes.sorted.chrLowered.gff3.gz",
		  color: "darkred",
		  indexed: true,
		  height: 300,
                  displayMode: "EXPANDED"
                  },
````

**Comment by paul-shannon** [comment]
This "ChrN" problem, assuming I have diagnosed it properly, appears to affect bigwig tracks as well.
My test case, inspired by [issue 241](https://github.com/igvteam/igv.js/issues/241)  is [DNase Hypersentivity Site data](http://plantdhs.org/static/download/Ath_buds_DNase.bw).  After seeing that this file, though found and loaded without reported errors, displays nothing, I used Bioconductor tools to examine a region of interest around the FRD3 gene on chr3:

````
R> fivenum(frd3.bw$score)  # [1] 0.2070 0.5810 0.8120 1.3525 8.6100
R> frd3.bw[frd3.bw$score > 8]
GRanges object with 82 ranges and 1 metadata column:
       seqnames             ranges strand |            score
          <Rle>          <IRanges>  <Rle> |        <numeric>
   [1]     Chr3 [2566693, 2566693]      * | 8.02200031280518
   [2]     Chr3 [2566694, 2566694]      * | 8.05700016021729
   [3]     Chr3 [2566695, 2566695]      * | 8.09000015258789
   [4]     Chr3 [2566696, 2566696]      * |  8.1230001449585
   [5]     Chr3 [2566697, 2566697]      * | 8.15499973297119
   ...      ...                ...    ... .              ...
  [78]     Chr3 [2566770, 2566770]      * | 8.15799999237061
  [79]     Chr3 [2566771, 2566771]      * |  8.1230001449585
  [80]     Chr3 [2566772, 2566772]      * | 8.08600044250488
  [81]     Chr3 [2566773, 2566773]      * | 8.05000019073486
  [82]     Chr3 [2566774, 2566774]      * | 8.01200008392334
  -------
````
which suggests that there is good data with plenty of signal in the bigwig file.  
After rewriting the chromosome names ("seqlevels" in bioc) to lowercase, and exporting a small bigwig file, the data displays nicely:
![image](https://user-images.githubusercontent.com/2480712/34420013-ecef52d6-ebbb-11e7-882a-a79cb5bf19a7.png)

Thus I think that TAIR-style chromosome names, with leading capital "C" elicits the problem in both gff and bigwig tracks.

**Comment by paul-shannon** [comment]
All of what you see below may be more of me barking up the wrong tree.  If so, I apologize!

The Athaliana fasta file starts

     >1 dna:chromosome chromosome:TAIR10:1:1:30427671:1 REF
      CCCTAAACCCTAAACCCTAAACCCTAAACCTCTGAATCCTTAATCCCTAAATCCCTAAAT
      CTTTAAATCCTACATCCATGAATCCCTAAATACCTAATTCCCTAAACCCGAAACCGGTTT

The problem I encountered  can be demonstrated using just the locus search box in the UI, after the above fasta reference track has been loaded.   (I believe that the silent failures  I observed when loading tracks programmatically, with ````ChrN```` rather than ````chrN````,  are related to what you can more simply reproduce in the search box.)

These two locus-naming styles work in the search box after the above fasta file is loaded as the reference track:

       N:start-end
       chrN:start-end

igv.js helpfully transforms ````chrN:```` to ````N:```` and maps it to the fasta sequence.  The ````N:start-end```` style locus is displayed in the search box after igv strips off the ````chr````.

But  using ````ChrN:start-end```` pops up the ````Unrecognized locus ...````  error dialog box.
I believe that, when loading tracks programmatically (small bed files I create on the fly from R), or other annotation tracks prepared by others, that ````ChrN:start-end```` loci are simply (and silently) dropped.

In practice, TAIR genome files and tracks seem to use that style:

    ChrN:start-end

Though of course the fasta file excerpted above omits the ````Chr````.
It may be narrowly self-serving for me to ask this - and it may skip over complexities I do not yet grasp  - but since igv.js already converts all ````chrN:start-end```` loci to ````N:start-end```` to agree with the fasta data, maybe it could also be case insensitive, and convert ````ChrN:start-end````to ````N:start-end```` as well?  

The alternative I see is for me to convert  annotation files to 'chrN' or simply "N".  Or modify the fasta file.  I will be glad to follow your lead on this.

Thank you for pointing out my ````gtf/gff3```` confusion.

**Comment by jrobinso** [comment]
So the problem is, in fact, a mismatch between fasta and gff/gtf3/wig
files.    What is the name of the "N" chromosome in the fasta file?   I am
guessing its  "N" since the first chromosome is "1".      Ideally, you
shouldn't have to rely on alias mapping hacks,  such as IGV does for "1" ->
"chr1".   If you have control of the fasta file here changing the names to
match your annotation files would fix the problem.   However there is an
easier way,  create a tab-delimited file of aliases and set it in the
property  "aliasURL" of your reference object.  The file should have 1 line
per chromosome with all possible names for the chromosome listed, in
arbitrary order.    So

1 <tab> Chr1
2 <tab> Chr2

etc.   Oddly this isn't documented, correcting that now.

**Comment by paul-shannon** [comment]
Sorry for my delay in testing this out.   I am not sure it (or I) has it quite right yet.

 Using igv.js grunted from the latest git pull, and a chromosome aliasURL in this reference configuration

     reference: {id: "hg38",
                     fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa",
                  cytobandURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/cytoBandIdeo.txt",
                     aliasURL: "http://trena.systemsbiology.net/hg38/chromosomeAliases.txt"

The relevant few lines from the  aliases file (tab-delimited text) looks like this -  unusual fifth name for chromosome 18 is designed to make sure aliases are being used rather than simple case-correction:

    17      Chr17   CHR17   chr17
    18      Chr18   CHR18   chr18   chrXVIII
    19      Chr19   CHR19   chr19

Then these work in the igv search box:

    aqp4
    AQP4
    chr18:26,851,038-26,863,910
    CHR18:26,851,038-26,863,910
    cHr18:26,851,038-26,863,910

but not

     chrXVIII:26,851,038-26,863,910

I see this in the javascript console:

    Unrecognized locus chrXVIII:26,851,038-26,863,910

Maybe I have misconstrued the technique?

 - Paul

**Comment by jrobinso** [comment]
Sorry about that, there were bugs.   I just pushed a fix.

**Comment by paul-shannon** [comment]
@jrobinso - I built igv.js after a fresh pull, but still see my idiosyncratic ````chrXVIII:start-stop```` fail.   The files I picked up don't, to my eye, have any obvious tie to chromosome aliases:
````
From https://github.com/igvteam/igv.js
   a2164c9f..45ade2d0  master     -> origin/master
Updating a2164c9f..45ade2d0
Fast-forward
 dev/bam.html               |  11 +++++++---
 dev/igv-dev.html           |   4 ++--
 dev/igv-oauth2.html        |   4 ++--
 js/igvxhr.js               |   8 ++++++-
 js/variant/variantTrack.js | 116 +++++++++++++...
 test/testBAM.js            |  28 +++++++++++++++++++++++-
````
Any suggestions?

**Comment by jrobinso** [comment]
Sorry, it looks like my push failed.   Try again, it should be there now.

**Comment by paul-shannon** [comment]
Seems to work just right - my silly chrXVIII:26,851,038-26,863,910 works perfectly.  I'll close this.  Thanks, @jrobinso!
