### ISSUE TITLE
sort by base function for alignment track not working

### ISSUE THREAD

**Issue by zengzheng123** [igvteam/igv.js#597]
Hi, It looks like "sort by base" function for alignment track is not working.

Best,
Zheng

**Comment by jrobinso** [comment]
@zengzheng123 could you give us more details? It's working for me.

**Comment by jrobinso** [comment]
Zheng, what version are you testing?  We just discovered that "sort by base" was present in the "cog" menu on the right of the track.  It should not have been there, that function has been moved to the right-click context menu.

**Comment by zengzheng123** [comment]
Hi, I was testing master branch code from two days ago. Yes, I was using the button in the "cog" menu.
I just tried the button in the right-click menu. It did resort the alignments, but they are not sorted by nucleotide. If I click the button again, the alignments are then sorted by nucleotide, but in reverse order(alignments that did not cover the location will be at the top, and alignments with alternative allele will be at the bottom). Then if I click the button one more time, the alignments are sorted correctly.

Btw, changing the "color by" option seems to change the order of the alignments, is this intended?

Best,
Zheng

**Comment by jrobinso** [comment]
Sorting repeatedly should just flip the order (ascending, descending).
 Are you able to reproduce the sort problem with
http://igv.org/web/test/examples/bam.html,  or other page that I can access?

The "color by" problem is another bug,  it forces an alignment track to
reload when it shouldn't.   That causes resorting.   When I track that down
the sort should be stable.

**Comment by zengzheng123** [comment]
The bam example page seems to work fine for me. The only problem I can find is if you go to chr8:128,752,178, "sort by base" several times, sometimes there is an alignment that does not cover the base is at the top, sometimes that alignment is near the bottom, among other alignments that do not cover that base. I'm not sure if it is because that alignment has soft clipping. But it is different from the problem I have. I will do some more testing tomorrow.

**Comment by zengzheng123** [comment]
Hi, I was able to reproduce the problem with your bam example page. If you goto chr1:850,309, and sort that position by base, it doesn't work for me on the first try.

**Comment by jrobinso** [comment]
This should be fixed.  The first sort was triggering a data reload,  which negated the sort.

**Comment by vemcshane** [comment]
Sort alignment by base still not working. Wont sort at all and is not checked in the option when selected.

**Comment by jrobinso** [comment]
Are you running from master, or a release?   I'm looking at it now.    It will never be checked,  this is an action not a state.

**Comment by jrobinso** [comment]
What version are you using?   I can reproduce the problem,  can you
reproduce it here

http://igv.org/web/release/2.0.0-beta3/examples/bam.html

or here

http://igv.org/web/test/test.html?

**Comment by jrobinso** [comment]
That's "can't reproduce the problem",  not "can reproduce the problem"  (corrected).

**Comment by apostonaut** [comment]
I think I have figured out the problem. On version 2.4.4, the default "black alignment bar" is not there, making it unclear which base one is "on". See this link:
https://github.com/griffithlab/rnaseq_tutorial/wiki/IGV-Tutorial#heterozygous-snps-on-different-alleles
In version 2.3, this "black alignment bar" is displayed, and the "sort alignment by base" function works when the black bar is aligned to the desired base.

**Comment by jrobinso** [comment]
The visibility of the alignment bar is a user preference,  you can set it
by selecting  "View > Preferences > Alignments tab".   I think its called
"show centerline".
